### ISSUE TITLE
Error in Tutorial 4: 'tuple' object has no attribute 'get_θ'

### ISSUE THREAD

**Issue by ysyysy115** [dl4to/dl4to#2]
Hi there,

I am trying to farmiliarize with dl4to, but when I try to train the NN follwing: 4_tutorial_trainable_topo_solvers.ipynb and run 

#ignore
topo_solver.train(
        root='training/cnn',
        epochs=50,
        dataloader_train=dataloader_train,
        dataloader_val=dataloader_val,
        validation_interval=10
)

I got the following error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [16], line 2
      1 #ignore
----> 2 topo_solver.train(
      3         root='training/cnn',
      4         epochs=50,
      5         dataloader_train=dataloader_train,
      6         dataloader_val=dataloader_val,
      7         validation_interval=10
      8 )

File /usr/local/lib/python3.9/dist-packages/dl4to/topo_solvers.py:816, in TrainableTopoSolver.train(self, root, dataloader_train, dataloader_val, epochs, validation_interval, verbose, patience)
    804 def train(self,
    805           root:str, # The directory where the training results should be saved.
    806           dataloader_train:torch.utils.data.DataLoader, # The dataloader that contains the training data.
   (...)
    811           patience:bool=None # If the validation score does not improve for `patience` epochs in a row, then the training is stopped and the best model is used.
    812          ):
    813     """
    814     Run the training for the topo solver.
    815     """
--> 816     self._train_module(
    817         root=root,
    818         dataloader_train=dataloader_train,
    819         dataloader_val=dataloader_val,
    820         epochs=epochs,
    821         validation_interval=validation_interval,
    822         verbose=verbose,
    823         patience=patience,
    824     )

File /usr/local/lib/python3.9/dist-packages/dl4to/topo_solvers.py:294, in TrainModule.__call__(self, root, dataloader_train, dataloader_val, epochs, validation_interval, verbose, patience)
    291 tick = time.time()
    293 for epoch in range(epochs):
--> 294     self._train_epoch(dataloader_train, epoch)
    295     validation_free_epoch = (validation_interval is None) or ((epoch % validation_interval != 0) and (epoch != epochs - 1))
    296     if validation_free_epoch:

File /usr/local/lib/python3.9/dist-packages/dl4to/topo_solvers.py:199, in TrainModule._train_epoch(self, dataloader, epoch)
    198 def _train_epoch(self, dataloader, epoch):
--> 199     train_loss, train_loss_std = self.epoch_module(dataloader=dataloader, train=True)
    200     self.solver.logs['train_epochs'].append(epoch)
    201     self.solver.logs['train_losses'].append(train_loss)

File /usr/local/lib/python3.9/dist-packages/dl4to/topo_solvers.py:179, in EpochLossGetter.__call__(self, dataloader, train)
    177 losses = []
    178 for problems_or_solutions, gt_solutions in dataloader:
--> 179     losses += self._run_batch(problems_or_solutions=problems_or_solutions, gt_solutions=gt_solutions, train=train)
    180 self.model.eval()
    181 return np.mean(losses), np.std(losses)

File /usr/local/lib/python3.9/dist-packages/dl4to/topo_solvers.py:162, in EpochLossGetter._run_batch(self, problems_or_solutions, gt_solutions, train)
    160 self._push_to_device(gt_solutions)
    161 solutions = self.solver(problems_or_solutions, eval_mode=not train)
--> 162 losses = self.solver.criterion(solutions, gt_solutions, binary=False)
    163 loss = losses.mean()
    164 if train:

File /usr/local/lib/python3.9/dist-packages/dl4to/criteria.py:324, in WeightedBCE.__call__(self, solutions, gt_solutions, binary)
    322 self._check_inputs(solutions, gt_solutions)
    323 θ = self.get_θ_flat(solutions, binary=binary)
--> 324 θ_true = self.get_θ_flat(gt_solutions, binary=binary)
    325 design_space_mask = self.get_design_space_mask(solutions)
    326 loss = binary_cross_entropy(
    327     θ * design_space_mask, θ_true * design_space_mask,
    328     weight=torch.tensor([self.weight], device=θ.device),
    329     reduction='none'
    330 )

File /usr/local/lib/python3.9/dist-packages/dl4to/criteria.py:58, in Criterion.get_θ_flat(self, solutions, binary)
     51 def get_θ_flat(self,
     52                solutions:list, # A list of solutions from which the densities are extracted and flattened into one output tensor.
     53                binary:bool=False # Whether the densities should be binarized.
     54               ):
     55     """
     56     Returns a flattened density distribution tensor from the passed solutions.
     57     """
---> 58     θ = torch.stack([solution.get_θ(binary=binary).flatten() for solution in solutions])
     59     θ.clamp_(0,1)
     60     return θ

File /usr/local/lib/python3.9/dist-packages/dl4to/criteria.py:58, in <listcomp>(.0)
     51 def get_θ_flat(self,
     52                solutions:list, # A list of solutions from which the densities are extracted and flattened into one output tensor.
     53                binary:bool=False # Whether the densities should be binarized.
     54               ):
     55     """
     56     Returns a flattened density distribution tensor from the passed solutions.
     57     """
---> 58     θ = torch.stack([solution.get_θ(binary=binary).flatten() for solution in solutions])
     59     θ.clamp_(0,1)
     60     return θ

AttributeError: 'tuple' object has no attribute 'get_θ'

May I ask how to resolve this, please?

Best,
Jason

**Comment by dl4to** [comment]
Thank you for pointing out the error. I fixed the issue in the latest push.

Regards,
David
