### ISSUE TITLE
There are issues with web-based drawing.

### ISSUE THREAD

**Issue by muyangren123321** [dl4to/dl4to#6]
I ran the code example in the tutorial about 'Problems and solutions', and all the other images are displaying correctly except for the Force directions.
This is my code.
```
import torch
from dl4to.problem import Problem
from dl4to.solution import Solution
from dl4to.criteria import Compliance, VolumeConstraint, VolumeFraction, Binariness, MaxStress
from dl4to.pde import FDM
from dl4to.topo_solvers import SIMP
E = 7e10
v = .3
sigma_ys = 4.5e8
shape = [40, 4, 8]
h = [0.0250, 0.0250, 0.0250]
F = torch.zeros(3, *shape)
F[0, :, :, -1] = -4e7
omiga_dirichlet = torch.zeros(3, *shape)
omiga_dirichlet[:, 0, :, :] = 1
omiga_design = -torch.ones(1, *shape)
omiga_design[:, :2, :, :] = 1
omiga_design[:, :, :, -2:] = 1.
problem = Problem(E, v, sigma_ys, h, omiga_dirichlet, omiga_design, F,
                  restrict_density_for_voxels_with_applied_forces=False)
problem.pde_solver = FDM()
print(problem.shape)
camera_position = (0, 0.35, 0.2)
criterion = Compliance() + VolumeConstraint(max_volume_fraction=.12, threshold_fct="relu")
problem.plot(camera_position=camera_position,show_axislabels=True,show_ticklabels=True, display=True)
```
![newplot (2)](https://github.com/user-attachments/assets/bb6f95cd-916b-42ed-a0f7-9a427c9a316c)
![newplot (3)](https://github.com/user-attachments/assets/49ccd45e-eb79-4549-b753-5ac848527f61)
![newplot (4)](https://github.com/user-attachments/assets/0a1ab2bd-61ec-4798-adea-ec0419b4d853)
![newplot (5)](https://github.com/user-attachments/assets/659b2f76-821a-45d9-aa49-85f2a5dbd2a0)

**Comment by dl4to** [comment]
Hello muyangren123321, on my end the plotting is working (it does look a bit messy because there are many arrows that all point in the same direction, but it is working - see the attached image). So this has to be something that is related to your imports. I have plotly 5.9.0 installed, do you maybe have a different version?


![newplot](https://github.com/user-attachments/assets/a4cb4114-736d-4fb5-b466-67eab6742465)

Greetings,
David

**Comment by muyangren123321** [comment]
Thank you for your reply, the issue has been successfully resolved. I previously had Plotly version 5.24.1, and after installing the same version as yours, the problem was solved.
