### ISSUE TITLE
There are significant disconnections in the structure.

### ISSUE THREAD

**Issue by muyangren123321** [dl4to/dl4to#8]
Dear author,

Hello! I am currently working on implementing the technical route of my thesis using the library you developed. As a beginner in learning and training with your library, I have some questions. First of all, I would like to express my gratitude for your prompt response to my inquiries, which I truly appreciate and makes me feel your enthusiasm.

The issue I am facing now is that I want to achieve the topological optimization of a beam that is fixed at both ends and subjected to forces from both the left and right directions. The code is as follows:

```
import torch
from dl4to.problem import Problem
from dl4to.solution import Solution
from dl4to.criteria import Compliance, VolumeConstraint,Fail,StressConstraint
from dl4to.pde import FDM
from dl4to.topo_solvers import SIMP

E = 2.1e11
ν = 0.3
σ_ys = 2.5e8
shape = [30, 4, 10]
h = [0.01, 0.01, 0.01]

F = torch.zeros(3, *shape)
F[0, -1, 1:3, 3:6] = 5e9
F[0, 1, 1:3, 3:6] = -5e9
Ω_dirichlet = torch.zeros(3, *shape)
Ω_dirichlet[:, 0, :, -2:] = 1
Ω_dirichlet[:, 0, :, :2] = 1
Ω_design = -torch.ones(1, *shape)
Ω_design[:, 0, :, -2:] = 1
Ω_design[:, 0, :, :2] = 1
camera_position = (0, 0.35, 0.2)
problem = Problem(E=E, ν=ν, σ_ys=σ_ys, h=h,
Ω_dirichlet=Ω_dirichlet, Ω_design=Ω_design, F=F,
restrict_density_for_voxels_with_applied_forces=False)
problem.plot(camera_position=camera_position,show_axislabels=True,show_ticklabels=True, display=True)
problem.pde_solver = FDM()
criterion = Compliance() + VolumeConstraint(max_volume_fraction=0.2, threshold_fct="relu") 

simp = SIMP(criterion=criterion, binarizer_steepening_factor=1., n_iterations=50, lr=3e-2)
solution = simp(problem)
print(solution.get_θ(binary=True).mean())

camera_position = (0, 0.35, 0.2)
solution.plot(solve_pde=True, binary=True, threshold=0.5)
```

The problem is that even after only 50 iterations, the final structure has a large area of disconnection and the volume fraction is only 0.0425, as shown in the figure below.
![newplot (11)](https://github.com/user-attachments/assets/8cc5b505-3f87-409a-9a62-2689c3a5b8db)

![newplot (12)](https://github.com/user-attachments/assets/3cb7191b-ab14-4f85-8f04-80daa8586cfc)

![newplot (13)](https://github.com/user-attachments/assets/8357f9b5-3f6e-4917-9cdc-1c3dfd4e7a73)
![newplot (14)](https://github.com/user-attachments/assets/000a4158-1e42-43fc-ba87-4e7802027d1e)
![newplot (15)](https://github.com/user-attachments/assets/86702233-4264-4132-b0ea-e1af3d5f6fec)

![newplot (16)](https://github.com/user-attachments/assets/3611f816-bb10-4aab-8176-53613ab70c96)
![newplot (17)](https://github.com/user-attachments/assets/0643e1e1-9a41-4a2b-be73-7ae9599b7ad7)

Therefore, I tried to use the StressConstraint and Fail from the library to limit this from happening, but it seems to have little effect. I also tried to modify the value of the threshold_fct parameter, which also seems to have no effect and even worse.
```
problem.plot(camera_position=camera_position,show_axislabels=True,show_ticklabels=True, display=True)
```
![newplot (18)](https://github.com/user-attachments/assets/c2bb5385-855b-4db9-b8f4-572ac2d83b45)
![newplot (19)](https://github.com/user-attachments/assets/9b829f2e-d513-45c6-a866-45ba92b37ba4)
![newplot (20)](https://github.com/user-attachments/assets/570cce1c-bffa-495d-af1a-f4429ab937f9)

In addition, I have noticed that there seems to be a problem with the training process printout. Therefore, I tried to install the same version of tqdm as you, but it does not seem to solve the problem.
![image](https://github.com/user-attachments/assets/b39afa85-b420-4ba2-86ac-4c609a41216d)

Once again, let me express my gratitude. When I encountered problems in the implementation of my technical route, it was your library that gave me new ideas. I noticed that you have not opened a sponsorship channel, but I would like to express my gratitude.

Best regards,
[muyangren]

**Comment by muyangren123321** [comment]
Is it because of some reasons that the library cannot handle situations where there are forces in two opposite directions or multiple force locations? Because I tried another case with forces in two opposite directions and encountered the same issue as described above.
```
import torch
from dl4to.problem import Problem
from dl4to.solution import Solution
from dl4to.criteria import Compliance, VolumeConstraint
from dl4to.pde import FDM
from dl4to.topo_solvers import SIMP

E = 2.1e11
ν = 0.3
σ_ys = 2.5e8
shape = [40, 4, 10]
h = [0.01, 0.01, 0.01]

F = torch.zeros(3, *shape)
F[-1, -1, 1:3, :2] = -5e9
F[-1, -1, 1:3, -2:] = 5e9
Ω_dirichlet = torch.zeros(3, *shape)
Ω_dirichlet[:, 0, :, -2:] = 1
Ω_dirichlet[:, 0, :, :2] = 1
Ω_design = -torch.ones(1, *shape)
Ω_design[:, 0, :, -2:] = 1
Ω_design[:, 0, :, :2] = 1
camera_position = (0, 0.35, 0.2)
problem = Problem(E=E, ν=ν, σ_ys=σ_ys, h=h,
Ω_dirichlet=Ω_dirichlet, Ω_design=Ω_design, F=F,
restrict_density_for_voxels_with_applied_forces=False)
problem.plot(camera_position=camera_position,show_axislabels=True,show_ticklabels=True, display=True)
problem.pde_solver = FDM()
criterion = Compliance() + VolumeConstraint(max_volume_fraction=0.2, threshold_fct="softplus")

simp = SIMP(criterion=criterion, binarizer_steepening_factor=1., n_iterations=150, lr=3e-2)
solution = simp(problem)
print(solution.get_θ(binary=True).mean())

camera_position = (0, 0.35, 0.2)
solution.plot(solve_pde=True, binary=True, threshold=0.5)
```

![newplot (21)](https://github.com/user-attachments/assets/256df881-b111-43fc-9030-768b39e4101d)
![newplot (22)](https://github.com/user-attachments/assets/bc0a38f0-9912-4c28-aa94-7932430ca83e)
![newplot (23)](https://github.com/user-attachments/assets/ac399543-e874-4ef9-9e5a-65cd7d78bea2)
![newplot (24)](https://github.com/user-attachments/assets/0bee6ee6-88dc-4745-80ee-fa00fee745e8)
![newplot (25)](https://github.com/user-attachments/assets/4effe5dd-11a5-4377-add3-85e94308fbf6)

**Comment by dl4to** [comment]
Dear muyangren123321,
thank you very much for your kind words and for appreciating this library and my work!
I tried out your code and I am not sure why it is not working (it is also not working on my end). Sometimes it is very hard to understand why numerical programs behave a certain way, especially if there are PDE solvers involved. I experimented a bit and I found that your code works if you change your first force to `F[0, -2:, 1:3, 3:6] = 5e9`, i.e., I changed the x coordinates slightly (I also made some small changes to the SIMP parameters like binarizer strength etc., I copied the full code below). I don't know why it is not working with your original settings. 

Also in my code it happens sometimes that the left force is not fully connected (there is one empty row). This is a known problem that sometimes happens with the finite differences PDE solver. It can be solved by using a padded PDE solver, `problem.pde_solver = FDM(padding_depth=1)`. This works more reliably, especially on low resolution grids, but it also takes more time to solve.

On a sidenote, please keep in mind that some problems can also occur if the resolution is low, i.e., if the number of voxels is low. Generally, the results look much better if you use a higher resolution, but then of course the simulations also take more time to solve.


`import torch
from dl4to.problem import Problem
from dl4to.solution import Solution
from dl4to.criteria import Compliance, VolumeConstraint,Fail,StressConstraint
from dl4to.pde import FDM
from dl4to.topo_solvers import SIMP

E = 2.1e11
ν = 0.3
σ_ys = 2.5e8
shape = [30, 4, 10]
h = [0.01, 0.01, 0.01]

F = torch.zeros(3, *shape)
F[0, -2:, 1:3, 3:6] = 5e9
F[0, 1, 1:3, 3:6] = -5e9
Ω_dirichlet = torch.zeros(3, *shape)
Ω_dirichlet[:, 0, :, -2:] = 1
Ω_dirichlet[:, 0, :, :2] = 1
Ω_design = -torch.ones(1, *shape)
Ω_design[:, 0, :, -2:] = 1
Ω_design[:, 0, :, :2] = 1
camera_position = (0, 0.35, 0.2)
problem = Problem(E=E, ν=ν, σ_ys=σ_ys, h=h,
Ω_dirichlet=Ω_dirichlet, Ω_design=Ω_design, F=F,
restrict_density_for_voxels_with_applied_forces=False)
#problem.plot(camera_position=camera_position,show_axislabels=True,show_ticklabels=True, display=True)
problem.pde_solver = FDM(padding_depth=1)
criterion = Compliance() + VolumeConstraint(max_volume_fraction=0.2, threshold_fct="relu") 

simp = SIMP(criterion=criterion, binarizer_steepening_factor=1.015, n_iterations=150, lr=5e-3)
solution = simp(problem)
print(solution.get_θ(binary=True).mean())

camera_position = (0, 0.35, 0.2)
solution.plot(solve_pde=True, binary=True, threshold=0.1)`

**Comment by dl4to** [comment]
Regarding your second question with tqdm: I have a tqdm version of 4.64.0, does this work for you?

**Comment by muyangren123321** [comment]
Oh, I was just about to ask you that question.
![image](https://github.com/user-attachments/assets/c2a1226f-8eb0-45d8-8537-6208e537d0ac)
![image](https://github.com/user-attachments/assets/c4c701f3-b62e-4c5b-bf66-d20b8f9a058b)

**Comment by dl4to** [comment]
Which IDE are you using? I am using jupyterlab and I remember that I needed to install some packages without which tqdm does not work properly. But I think that this is mainly a jupyterlab-thing. Something like

pip install -U jupyterlab-widgets==1.0.0
pip install -U ipywidgets==7.6.5

(these are my versions, maybe newer versions work too)
Does this help?

**Comment by muyangren123321** [comment]
I use PyCharm as my editor, and when I train deep learning models using tqdm, the progress bar display works perfectly fine.

**Comment by dl4to** [comment]
I have made a new commit to the library, where I changed the line `from tqdm.notebook import tqdm` to `from tqdm import tqdm`. Does it work now?

**Comment by muyangren123321** [comment]
Dear author, thank you for your work. I appreciate your modifications, and now tqdm is functioning properly.
